# -*- coding: utf-8 -*-
"""01_preprocess_binary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ShvDoSr5goKeDbgOYgrXksXZ2KDoUm49
"""

import pandas as pd
import numpy as np
import ast
import re
import os
import json

"""Pasos realizados para la limpieza (Versión Binaria):

- **Filtrado de columnas irrelevantes y purga de RAM**: Eliminación temprana de campos inútiles (URLs, nombres, imágenes, webs) junto con la exclusión drástica de textos masivos de descripciones para optimizar al máximo la memoria de Colab.

- **Eliminación de filas sin métricas de rendimiento**: Filtro radical que expulsa cualquier juego que carezca de datos críticos en el lanzamiento (peak_ccu, tags, num_reviews_total) para evitar meter registros corruptos al modelo.

- **Acotación del contexto Indie y filtrado de gigantes**: Identificación automatizada del subsector independiente mediante análisis de géneros y etiquetas, limitando el dataset a títulos con un volumen de copias realista ($\le$ 5 millones) para suprimir los outliers absolutos de la industria.

- **Target binario adaptado al baremo de la comunidad**: Cálculo del éxito comercial excluyendo la prensa tradicional (metacritic_score) y aplicando una normalización por percentiles (p01-p99) para que los éxitos masivos no rompan la escala; el corte final se fija en la mediana (p50) para balancear el modelo en un 50/50 puro de Éxito o Fracaso.

- **Ingeniería de variables de mercado y localización**: Sustitución del conteo simple de idiomas por un índice de mercado ponderado por regiones de Steam, y adición de métricas de marketing en tienda (n_screenshots, n_movies, n_achievements) capadas estadísticamente al percentil 95 para neutralizar el spam de logros y fotos.

- **Estandarización temporal libre de sesgo**: Eliminación del año continuo para que la Inteligencia Artificial no sufra un sesgo de supervivencia lineal respecto al futuro, conservando únicamente el trimestre de lanzamiento (release_quarter) para capturar la estacionalidad del negocio.

- **Reestructuración del índice y exportación de metadatos**: Reordenación del DataFrame final forzando al appid como la primera columna de la izquierda y guardado persistente de las constantes de normalización en un JSON para poder alimentar la app del simulador.
"""

"""
01_preprocess_binary.py
=======================
Versión: CLASIFICACIÓN BINARIA (Fracaso vs Éxito)
Limpieza, ingeniería de features y cálculo del success_score.
Ajustado para contexto INDIE con blindaje metodológico (Pablo Colomino).

Genera: data/processed_binary.parquet y models/thresholds_binary.json
"""

# Rutas del proyecto
RAW_PATH = "data/games_march2025_cleaned.csv"
OUT_PATH = "data/processed_binary.parquet"
JSON_PATH = "models/thresholds_binary.json"

# ─────────────────────────────────────────────
# HELPERS PARSEO (alaizar cadena textos)
# ─────────────────────────────────────────────
def parse_list_col(s):
    if pd.isna(s): return []
    try:
        return [x.strip() for x in ast.literal_eval(str(s))]
    except:
        return [x.strip() for x in str(s).split(",")]

def parse_owners(s):
    if pd.isna(s): return np.nan
    m = re.findall(r"\d+", str(s).replace(",", ""))
    if len(m) >= 2: return (int(m[0]) + int(m[1])) / 2
    elif len(m) == 1: return int(m[0])
    return np.nan

# ─────────────────────────────────────────────
# 1. CARGA ROBUSTA
# ─────────────────────────────────────────────
print("Cargando dataset con motor tolerante...")
df = pd.read_csv(
    RAW_PATH,
    engine='python',
    on_bad_lines='skip'
)
print(f"  Shape inicial: {df.shape}")

# ─────────────────────────────────────────────
# 2. PURGA Y LIMPIEZA
# ─────────────────────────────────────────────
# Eliminamos columnas inútiles para aliviar memoria, salvamos appid
cols_to_drop = [
    'name', 'dlc_count', 'developers', 'reviews', 'header_image',
    'website', 'support_url', 'support_email', 'metacritic_url',
    'notes', 'packages', 'screenshots', 'movies', 'score_rank', 'discount',
    'detailed_description', 'about_the_game', 'short_description'
]

df_clean = df.drop(columns=[c for c in cols_to_drop if c in df.columns]).copy()

# la IA aprende que descripcion mas larga = mas exito, no conviene esto asi que DESCARTAMOS DECSRIPCIONES (no se usa)

# Gestión de descripciones vacías en texto
# desc_cols = ['detailed_description', 'about_the_game', 'short_description']
# for col in desc_cols:
#    if col in df_clean.columns:
#       df_clean[col] = df_clean[col].fillna("No description")


# Filtro crítico pre-lanzamiento e indies muertos (NaNs)
df_clean = df_clean.dropna(subset=['peak_ccu', 'tags', 'num_reviews_total'])

# ─────────────────────────────────────────────
# 3. IDENTIFICAR CONTEXTO INDIE
# ─────────────────────────────────────────────
genre_col = "genres" if "genres" in df_clean.columns else "genre"
df_clean["genres_list"] = df_clean[genre_col].apply(parse_list_col) if genre_col in df_clean.columns else pd.Series([[] for _ in range(len(df_clean))], index=df_clean.index)
df_clean["tags_list"] = df_clean["tags"].apply(parse_list_col) if "tags" in df_clean.columns else pd.Series([[] for _ in range(len(df_clean))], index=df_clean.index)

def is_indie_check(row):
    genres = [g.lower() for g in row["genres_list"]]
    tags = [t.lower() for t in row["tags_list"]]
    return int("indie" in genres or "indie" in tags)

df_clean["is_indie"] = df_clean.apply(is_indie_check, axis=1)

# Filtrar los Gigantes (Outliers de mercado absoluto)
df_clean["estimated_owners_num"] = df_clean["estimated_owners"].apply(parse_owners)
df_clean = df_clean[df_clean['owners_midpoint'] <= 5000000].copy() if 'owners_midpoint' in df_clean.columns else df_clean[df_clean['estimated_owners_num'] <= 5000000].copy()

# Filtro estricto para calcular umbrales (Evita compresión hacia el cero)
indie_active_mask = (
    (df_clean["is_indie"] == 1) &
    (df_clean["estimated_owners_num"] > 0) &
    (df_clean["num_reviews_total"] > 100)
)
df_indie_active = df_clean[indie_active_mask]

# ─────────────────────────────────────────────
# 4. TARGET: SUCCESS SCORE (Exclusivo Comunidad)
# ─────────────────────────────────────────────
# Pesos corregidos (Métricas puras de mercado) -> Descartamos uso de metacritic score
score_cols = {
    "estimated_owners_num": 0.45,
    "peak_ccu": 0.30,
    "num_reviews_total": 0.15,
    "pct_pos_total": 0.10
}

# Forzar numéricos
for c in score_cols.keys():
    if c in df_clean.columns:
        df_clean[c] = pd.to_numeric(df_clean[c], errors="coerce").fillna(0)

# Normalización adaptada al baremo Indie (p01 - p99)
normed = {}
indie_norm_params = {}
for col in score_cols:
    s = df_clean[col].copy()
    indie_vals = df_indie_active[col].dropna()

    cap = indie_vals.quantile(0.99) if len(indie_vals) > 0 else s.quantile(0.99)
    floor = indie_vals.quantile(0.01) if len(indie_vals) > 0 else s.quantile(0.01)

    indie_norm_params[col] = {"floor": float(floor), "cap": float(cap)}

    s = s.clip(lower=floor, upper=cap).fillna(floor)
    normed[col + "_norm"] = (s - floor) / (cap - floor + 1e-9)

normed_df = pd.DataFrame(normed, index=df_clean.index)
df_clean = pd.concat([df_clean, normed_df], axis=1)

df_clean["success_score"] = sum(df_clean[col + "_norm"] * w for col, w in score_cols.items()) * 100

# CLASIFICACIÓN BINARIA: Calculamos la mediana (p50) de los indies activos
p50 = float(df_clean.loc[indie_active_mask, "success_score"].quantile(0.50))

# 0 = Fracaso (mitad inferior), 1 = Éxito (mitad superior)
df_clean["success_class"] = df_clean["success_score"].apply(lambda s: 1 if s >= p50 else 0)

# ─────────────────────────────────────────────
# 5. FEATURE ENGINEERING (Inputs Pre-Lanzamiento)
# ─────────────────────────────────────────────

# --- Precio ---
df_clean["price"] = pd.to_numeric(df_clean.get("price", np.nan), errors="coerce").fillna(0)
df_clean["is_free"] = (df_clean["price"] == 0).astype(int)

# --- Edad requerida ---
df_clean["required_age"] = pd.to_numeric(df_clean.get("required_age", 0), errors="coerce").fillna(0)

# --- Plataformas ---
for plat in ["windows", "mac", "linux"]:
    if plat in df_clean.columns:
        df_clean[f"plat_{plat}"] = df_clean[plat].map({True: 1, False: 0, "True": 1, "False": 0}).fillna(0).astype(int)
    else:
        df_clean[f"plat_{plat}"] = 0

# --- Multiplayer ---
def has_multiplayer(tags):
    if pd.isna(tags): return 0
    return int("multiplayer" in str(tags).lower() or "co-op" in str(tags).lower())
df_clean["is_multiplayer"] = df_clean["tags"].apply(has_multiplayer)

# --- SCORE PONDERADO DE IDIOMAS (Market Share Real) ---
LANGUAGE_WEIGHTS = {
    "English": 1.00, "Simplified Chinese": 0.85, "Russian": 0.55,
    "German": 0.45, "French": 0.40, "Spanish - Spain": 0.35, "Portuguese - Brazil": 0.33,
    "Japanese": 0.30, "Korean": 0.28, "Polish": 0.22, "Turkish": 0.20,
    "Traditional Chinese": 0.18, "Italian": 0.17, "Dutch": 0.15,
    "Spanish - Latin America": 0.15, "Czech": 0.13, "Hungarian": 0.12,
    "Romanian": 0.11, "Swedish": 0.10, "Norwegian": 0.09, "Danish": 0.09,
    "Finnish": 0.08, "Ukrainian": 0.08, "Thai": 0.07, "Arabic": 0.07, "Portuguese - Portugal": 0.06
}
LANGUAGE_WEIGHTS_DEFAULT = 0.04

def calculate_language_score(s):
    langs = parse_list_col(s)
    if not langs: return 0
    return sum(LANGUAGE_WEIGHTS.get(l, LANGUAGE_WEIGHTS_DEFAULT) for l in langs)

df_clean["languages_market_score"] = df_clean.get("supported_languages", pd.Series(dtype=str)).apply(calculate_language_score)

# --- MULTIMEDIA Y LOGROS (Con Tope / Clip para evitar Spam) ---
# Extraemos o forzamos las columnas numéricas basándonos en tu EDA
for col in ["n_screenshots", "n_movies", "n_achievements"]:
    # Si vienen de las columnas crudas de steam (ej: screenshots tiene strings de listas), contamos longitud
    if col not in df_clean.columns and col.replace("n_", "") in df.columns:
        df_clean[col] = df.get(col.replace("n_", "")).apply(lambda x: len(parse_list_col(x)))
    else:
        df_clean[col] = pd.to_numeric(df_clean.get(col, 0), errors="coerce").fillna(0)

# Aplicamos capado estadístico al p95 sobre el subconjunto indie activo
for col in ["n_screenshots", "n_movies", "n_achievements"]:
    cap_val = df_clean.loc[indie_active_mask, col].quantile(0.95)
    df_clean[col] = df_clean[col].clip(upper=cap_val)

# --- Géneros y Tags (Filtro enfocado a la masa Indie) ---
indie_mask = df_clean["is_indie"] == 1
indie_genre_counts = pd.Series([g for lst in df_clean.loc[indie_mask, "genres_list"] for g in lst]).value_counts()
TOP_GENRES = indie_genre_counts.head(15).index.tolist()

for g in TOP_GENRES:
    safe = re.sub(r"[^a-z0-9]", "_", g.lower())
    df_clean[f"genre_{safe}"] = df_clean["genres_list"].apply(lambda lst: int(g in lst))

indie_tag_counts = pd.Series([t for lst in df_clean.loc[indie_mask, "tags_list"] for t in lst]).value_counts()
TOP_TAGS = indie_tag_counts.head(30).index.tolist()

for t in TOP_TAGS:
    safe = re.sub(r"[^a-z0-9]", "_", t.lower())
    df_clean[f"tag_{safe}"] = df_clean["tags_list"].apply(lambda lst: int(t in lst))

# --- Publisher: Leave-One-Out (Evita Data Leakage) ---
pub_col = "publishers" if "publishers" in df_clean.columns else "publisher"
df_clean["publisher_clean"] = df_clean[pub_col].apply(lambda s: parse_list_col(s)[0] if parse_list_col(s) else "Unknown")

pub_sum = df_clean[indie_active_mask].groupby("publisher_clean")["success_score"].sum()
pub_count = df_clean[indie_active_mask].groupby("publisher_clean")["success_score"].count()
unknown_pubs = set(df_clean["publisher_clean"]) - set(pub_count[pub_count >= 3].index)
self_published_mask = indie_active_mask & df_clean["publisher_clean"].isin(unknown_pubs)
self_published_avg = float(df_clean.loc[self_published_mask, "success_score"].mean())

def publisher_avg_loo(row):
    pub = row["publisher_clean"]
    score = row["success_score"]
    if pub not in pub_sum.index or pub_count[pub] < 3:
        return self_published_avg
    count = pub_count[pub]
    return (pub_sum[pub] - score) / (count - 1)

df_clean["publisher_success_avg"] = df_clean.apply(publisher_avg_loo, axis=1)

# --- FECHAS (Solo trimestre para Estacionalidad) ---
if "release_date" in df_clean.columns:
    df_clean["release_date_parsed"] = pd.to_datetime(df_clean["release_date"], errors="coerce")
    df_clean["release_quarter"] = df_clean["release_date_parsed"].dt.quarter.fillna(0).astype(int)

# ─────────────────────────────────────────────
# 6. LIMPIEZA DE COLUMNAS TEMPORALES Y ORDENACIÓN
# ─────────────────────────────────────────────
norm_cols = [col + "_norm" for col in score_cols.keys()]
cols_to_remove = norm_cols + ["publisher_clean", "genres_list", "tags_list", "release_date_parsed"]
df_clean = df_clean.drop(columns=[c for c in cols_to_remove if c in df_clean.columns])

# Forzamos que 'appid' sea la primera columna a la izquierda y purgamos 'name'
cols = ['appid'] + [c for c in df_clean.columns if c not in ['appid', 'name']]
df_clean = df_clean[cols]

# ─────────────────────────────────────────────
# 7. GUARDAR METADATOS (Para tu Simulador Web)
# ─────────────────────────────────────────────
os.makedirs("data", exist_ok=True)
os.makedirs("models", exist_ok=True)

thresholds_binary = {
    "p50": p50,
    "self_published_avg": self_published_avg,
    "norm_params": indie_norm_params,
    "top_genres": TOP_GENRES,
    "top_tags": TOP_TAGS,
    "score_weights": score_cols,
}

with open(JSON_PATH, "w") as f:
    json.dump(thresholds_binary, f, indent=2)

df_clean.to_parquet(OUT_PATH, index=False)

print(f"\n✅ Pipeline BINARIO completado con éxito.")
print(f"Filas resultantes: {len(df_clean)} | Columnas finales: {df_clean.shape[1]}")
print(f"Distribución Clases:")
print(df_clean["success_class"].value_counts().sort_index().rename({0: "0: Fracaso", 1: "1: Éxito"}))









