# -*- coding: utf-8 -*-
"""Preprocess-Pablo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ShvDoSr5goKeDbgOYgrXksXZ2KDoUm49
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files # Esta es específica para subir archivos

"""Pasos realizados para la limpieza:
- Filtrado de columnas irrelevantes (url, nombres, img)
- Salvaguardas textos (mantener descripciones y autorellenar con "No description")
- Eliminación de filas sin métricas de rendimiento (juegos sin datos clave)
- Estandarización de fechas (fecha en texto plano y añadir column de release_year)
- Conversión de rangos comerciales a valores numéricos (owners_midpoint para estimar rangos)
- Reestructuración del índice (forzar columna indice a ser la primera)

Recomendaciones de limpieza:
- Filtrar los gigantes de la industria (cs2, dota)-solo indies
- Codificacion de generos (Accion 0, Rol, 1 - [Cada genero una columna independiente 0-no es de ese genero, 1 - si es])
- Diferenciar gratuitos con columna indepeneidente (0-no es, 1- si es)
- Normalización de variables de impacto (Aplicar una transformación logarítmica (np.log1p) a las columnas de jugadores y dueños.)
"""

df = pd.read_csv(
    'games_march2025_cleaned.csv',
    engine='python',
    on_bad_lines='skip'
)

# 1. Ver las columnas y tipos de datos
print("--- COLUMNAS ---")
print(df.info())

# 2. Ver una muestra de los datos reales
print("\n--- PRIMERAS FILAS ---")
print(df.head().to_csv())

# 3. Ver cuántos valores faltantes hay (importante para limpiar)
print("\n--- VALORES NULOS ---")
print(df.isnull().sum())

# ─────────────────────────────────────────────────────────────────────────────
# 1. Lista de columnas a eliminar
# ─────────────────────────────────────────────────────────────────────────────
cols_to_drop = [
    'name', 'dlc_count', 'achievements', 'developers',
    'reviews', 'header_image', 'website', 'support_url',
    'support_email', 'metacritic_url', 'notes', 'packages',
    'screenshots', 'movies', 'score_rank', 'discount'
]

# Aplicamos la limpieza asegurándonos de que 'appid' NO esté en la lista negra
df_clean = df.drop(columns=[c for c in cols_to_drop if c in df.columns]).copy()

# ─────────────────────────────────────────────────────────────────────────────
# 2. Gestión de descripciones y valores nulos
# ─────────────────────────────────────────────────────────────────────────────
desc_cols = ['detailed_description', 'about_the_game', 'short_description']
for col in desc_cols:
    if col in df_clean.columns:
        df_clean[col] = df_clean[col].fillna("No description")

# Limpieza de filas críticas (mantenemos solo juegos con datos de comunidad)
df_clean = df_clean.dropna(subset=['peak_ccu', 'tags', 'num_reviews_total'])

# Procesamiento de fechas y conversión de Owners a número
df_clean['release_date'] = pd.to_datetime(df_clean['release_date'], errors='coerce')
df_clean['release_year'] = df_clean['release_date'].dt.year

def parse_owners(owner_str):
    if pd.isna(owner_str) or '-' not in str(owner_str):
        return 0
    parts = str(owner_str).replace(',', '').replace(' ', '').split('-')
    try:
        low, high = map(int, parts)
        return (low + high) / 2
    except:
        return 0

df_clean['owners_midpoint'] = df_clean['estimated_owners'].apply(parse_owners)

df_clean['owners_midpoint'] = df_clean['estimated_owners'].apply(parse_owners)

# Asegurar que las columnas del target sean estrictamente numéricas
for c in ["metacritic_score", "peak_ccu", "positive", "negative", "recommendations", "num_reviews_total"]:
    if c in df_clean.columns:
        df_clean[c] = pd.to_numeric(df_clean[c], errors="coerce").fillna(0)

# Filtrar los "Gigantes" de la industria para enfocarnos en mercado Indie/Mediano
# Eliminamos juegos con más de 5 millones de copias estimadas
df_clean = df_clean[df_clean['owners_midpoint'] <= 5000000].copy()

# Identificar si el juego es gratuito (Free to Play)
df_clean['is_free'] = (df_clean['price'] == 0).astype(int)

# ─────────────────────────────────────────────────────────────────────────────
# 3. Cálculo Target: Succes Score (0-100)
# ─────────────────────────────────────────────────────────────────────────────
def parse_list_col(s):
    if pd.isna(s): return []
    try: return [x.strip() for x in ast.literal_eval(str(s))]
    except: return [x.strip() for x in str(s).split(",")]

pub_col = "publishers" if "publishers" in df_clean.columns else "publisher"
df_clean["publisher_clean"] = df_clean[pub_col].apply(lambda s: parse_list_col(s)[0] if parse_list_col(s) else "Unknown")

# Contamos el volumen de lanzamientos por distribuidora
pub_counts = df_clean["publisher_clean"].value_counts()

# Filtramos solo los que tengan un histórico sólido (mínimo 3 juegos en el dataset)
valid_publishers = pub_counts[pub_counts >= 3].index

# Calculamos el éxito base inicial de la comunidad para mapear los publishers
# Usamos una métrica temporal de rendimiento (ventas + jugadores) para darles el peso inicial
df_clean['temp_perf'] = (df_clean['owners_midpoint'] * 0.6) + (df_clean['peak_ccu'] * 0.4)
pub_means = df_clean[df_clean["publisher_clean"].isin(valid_publishers)].groupby("publisher_clean")['temp_perf'].mean()

# Escalamos el peso de los publishers robustos de 0 a 100
p_min, p_max = pub_means.min(), pub_means.max()
pub_means_scaled = ((pub_means - p_min) / (p_max - p_min + 1e-9)) * 100
publisher_weight_map = pub_means_scaled.to_dict()

# Mapeamos los pesos al dataset principal. Los de < 3 juegos se quedan con 0
df_clean["publisher_weight"] = df_clean["publisher_clean"].map(publisher_weight_map).fillna(0)

# ─────────────────────────────────────────────────────────────────────────────
# 4. Lógica de pesos en publishers (mínimo 3 juegos y de 0-100)
# ─────────────────────────────────────────────────────────────────────────────
# Nota híbrida de calidad: Si Metacritic es 0, usamos las reseñas de los usuarios
df_clean['quality_score'] = df_clean.apply(
    lambda x: (x['metacritic_score'] + x['pct_pos_total']) / 2 if x['metacritic_score'] > 0 else x['pct_pos_total'],
    axis=1
)

# Definimos las columnas del éxito final
score_cols = {
    "owners_midpoint": 0.40,
    "peak_ccu": 0.25,
    "num_reviews_total": 0.20,
    "quality_score": 0.15
}

# Normalizamos las columnas del éxito controlando outliers con el Percentil 99 (p99)
normed = {}
for col, weight in score_cols.items():
    s = df_clean[col].copy()
    cap = s.quantile(0.99)
    s = s.clip(upper=cap)
    s_min, s_max = s.min(), s.max()
    normed[col + "_norm"] = (s - s_min) / (s_max - s_min + 1e-9)

normed_df = pd.DataFrame(normed, index=df_clean.index)
df_clean = pd.concat([df_clean, normed_df], axis=1)

# Generamos la nota final del éxito de 0 a 100 (Resultado Comercial Puro)
df_clean["success_score"] = sum(
    df_clean[col + "_norm"] * w for col, w in score_cols.items()
) * 100

# Transformamos la nota continua a clases/categorías discretas de éxito
df_clean["success_class"] = df_clean["success_score"].apply(lambda s: 0 if s < 35 else (1 if s < 65 else 2))

# Limpieza de columnas temporales
df_clean = df_clean.drop(columns=[col + "_norm" for col in score_cols.keys()] + ["publisher_clean", "temp_perf"])

# ─────────────────────────────────────────────────────────────────────────────
# 5. Ordenar columnas y confirmar
# ─────────────────────────────────────────────────────────────────────────────
# Forzamos que 'appid' sea la primera columna a la izquierda
cols = ['appid'] + [c for c in df_clean.columns if c not in ['appid', 'name']]
df_clean = df_clean[cols]

print(f"✅ Dataset final listo para Machine Learning.")
print(f"Filas resultantes (indies filtrados): {len(df_clean)}")
print(f"Distribución de la variable objetivo (clases):")
print(df_clean["success_class"].value_counts().sort_index().rename({0:"Fracaso", 1:"Moderado", 2:"Éxito"}))
print("\nColumnas del DataFrame final:")
print(df_clean.columns.tolist())











